_target_: core.trainers.ultralytics.UltralyticsTrainer

export_onnx: true
onnx_export_args:
  simplify: false

args:
  data: "configs/fsoco.yaml"
  epochs: 50
  imgsz: 640
  batch: 16
  project: "models/fine_tuned"
