_target_: core.loggers.gitlab_mlflow.GitLabMLflowLogger
experiment_name: "fsoco_cone_detection"
tracking_uri: ${oc.env:MLFLOW_TRACKING_URI,null}
val_image_path: "data/fsoco/preprocessed/images/val/sample.jpg"
