defaults:
  - trainer: ultralytics
  - dataset: fsoco
  - metric/train_losses@metrics.train_losses
  - metric/learning_rates@metrics.learning_rates
  - metric/validation@metrics.validation
  - metric/fitness@metrics.fitness
  - _self_

model:
  name: "yolo11n"
  weights: "yolo11n.pt"

loggers:
  #gitlab:
  #  _target_: core.loggers.gitlab_mlflow.GitLabMLflowLogger
  wandb:
    _target_: core.loggers.wandb.WandBLogger

run_name: "${model.name}_${now:%Y%m%d_%H%M%S}"

hydra:
  run:
    dir: outputs/${run_name}
